//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.12 at 12:02:24 AM CET 
//


package com.example.departement;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="etudiants" type="{http://example.com/departement}ListeEtudiantsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "etudiants"
})
@XmlRootElement(name = "getAllEtudiantsResponse")
public class GetAllEtudiantsResponse {

    @XmlElement(required = true)
    protected ListeEtudiantsType etudiants;

    /**
     * Gets the value of the etudiants property.
     * 
     * @return
     *     possible object is
     *     {@link ListeEtudiantsType }
     *     
     */
    public ListeEtudiantsType getEtudiants() {
        return etudiants;
    }

    /**
     * Sets the value of the etudiants property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListeEtudiantsType }
     *     
     */
    public void setEtudiants(ListeEtudiantsType value) {
        this.etudiants = value;
    }

}
