//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.12 at 12:03:24 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://example.com/departement", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.departement;
